### ISSUE TITLE
How can I start training ?

### ISSUE THREAD

**Issue by moonsh** [NotAnyMike/HRL#93]
Hi, First, thank you for sharing your work.
I have a quick look at your description of your work.
But I couldn't find how I can start training.
Could you explain this? Thank you,

**Comment by NotAnyMike** [comment]
Thanks (: 
So training is the same as running experiments in the readme. So if you follow the "run experiments" section you should be ok

**Comment by moonsh** [comment]
@NotAnyMike  Thank you.
